version: '3.8'
services:
  app:
    build: .
    ports:
      - "3000:3000"
    volumes:
      - .:/app
    environment:
      - NODE_ENV=development
      - DATABASE_URL=postgres://postgres:password@db:5432/infrastructure
      - JWT_SECRET=supersecret
    depends_on:
      - db

  db:
    image: postgres:16
    restart: always
    environment:
      POSTGRES_PASSWORD: password
      POSTGRES_DB: infrastructure
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata: